export const FETCH_DATA = "FETCH_DATA";
export const ADD_DATA = "ADD_DATA";
export const UPDATE_DATA = "UPDATE_DATA";
export const DELETE_DATA = "DELETE_DATA";

export const FETCH_RESTAURANT = "FETCH_RESTAURANT";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const EDIT_RESTAURANT = "EDIT_RESTAURANT";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";

// Người dùng
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const CREATE_USER = "CREATE_USER";
export const APPLICATION = "APPLICATION";
export const UPDATE_USER = "UPDATE_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";

// Sảnh
export const FETCH_SANH_NHA_HANG = "FETCH_SANH_NHA_HANG";
export const FETCH_TAT_CA_SANH = "FETCH_TAT_CA_SANH";
export const DELETE_SANH = "DELETE_SANH";
export const CREATE_SANH = "CREATE_SANH";
export const EDIT_SANH = "EDIT_SANH";
export const UPDATE_SANH = "UPDATE_SANH";

// Nhân viên
export const FETCH_NHANVIEN = "FETCH_NHANVIEN";
export const EDIT_NHANVIEN = "EDIT_NHANVIEN";
export const UPDATE_NHANVIEN = "UPDATE_NHANVIEN";
export const CREATE_NHANVIEN = "CREATE_NHANVIEN";
export const DELETE_NHANVIEN = "DELETE_NHANVIEN";

// Chức vụ nhân viên
export const FETCH_CHUCVU_NHANVIEN = "FETCH_CHUCVU_NHANVIEN";
export const EDIT_CHUCVU_NHANVIEN = "EDIT_CHUCVU_NHANVIEN";
export const UPDATE_CHUCVU_NHANVIEN = "UPDATE_CHUCVU_NHANVIEN";
export const CREATE_CHUCVU_NHANVIEN = "CREATE_CHUCVU_NHANVIEN";
export const DELETE_CHUCVU_NHANVIEN = "DELETE_CHUCVU_NHANVIEN";

// Danh mục
export const DANH_MUC_CHUC_VU_NHAN_VIEN = "DANH_MUC_CHUC_VU_NHAN_VIEN";

// Booking
export const BOOKING_RESTAURANT_ROOM_REQUEST = "BOOKING_RESTAURANT_ROOM_REQUEST";
export const FETCH_BOOKING_ROOM = "FETCH_BOOKING_ROOM";
export const DELETE_BOOKING_ROOM = "DELETE_BOOKING_ROOM";

export const FETCH_SERVICES = "FETCH_SERVICES";
export const EDIT_SERVICES = "EDIT_SERVICES";

// comment
export const FETCH_COMMENT = "FETCH_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";


// Location
export const FETCH_LOCATION = "FETCH_LOCATION";